title: Professional Portfolio 
email: carlos.mendez@unesp.br
description: Geosciences| Hydro energy | Hidrometeorology | Agrometeorology | Geotechnologies - GIS | GeoAI-ML-DL
twitter_username: username
github_username: CarlosMendez1997Col
minimal_mistakes_skin: neon
search: true

<h1 align="center">Welcome to my GitHub👋, I'm Carlos Mendez 👨🏽‍💻 </h1>

![Cartographic and Geodesic Engineer, Master in Geosciences and Environment  (1)](https://github.com/user-attachments/assets/5d443f4f-52c8-4702-9a5f-49954c4bbc4b)

<h2 align="left">Professional profile👷🏽 </h2>

<h5 align="justify"> Cadastral and Geodesic Engineer, MSc in Geosciences and Environment at São Paulo State University (UNESP), with professional experience in the leadership of technical-scientific teams, offering useful solutions for modeling, forecasting, analysis and decision making in areas related with: </h5>

<h5 align="justify">
 Hydroenergy and renewable energies: 
 
- Evaluation and simulation of inputs and reserves in hydroelectric power plants referring to Daily Useful Volume (Mm3), Energy Useful Volume (kWh), Energy Inputs (kWh), Flow Inputs (m3/s), 95 PSS Energy Inputs (kWh) and 95 PSS Flow Inputs (m3/s) using Artificial Intelligence algorithms such as: Auto Regressive Neural Networks (NNAR), Long Short-Term Memory (LSTM) and ResCNNN.</h5>


<h5 align="justify">
 Hydrometeorology:
 
- Evaluation of extreme hydrometeorological phenomena such as droughts and low water periods, using the Standardized Precipitation Index (SPI), the Standardized Precipitation-Evapotranspiration Index (SPEI) and the Palmer Drought Severity Index (PDSI), in reference to hydrological terms such as water scarcity, water stress and water availability. </h5>


<h5 align="justify">
Climate Change:
 
- Evaluation of climate change scenarios SSP2-4.5, SSP3-7.0, SPP5-8.5 and bioclimatic projections using Global Climate Models (GCM) CCma-CanESM2, MOHC-HadGEM2-ES and MIROC-MIROC5 in ArcGIS API for Python and ArcGIS Maps SDK for JavaScript.</h5>

 <h5 align="justify">
  Water Resources:
  
- Monitoring and control of water resources, surface and groundwater, water balance using satellite images in Cloud-Computing systems such as Google Earth Engine (GEE) and JavaScript language.
- Hydrological analysis of HydroSHEDS, HydroATLAS, HydroBASINS, HydroLAKES, HydroRIVERS, Global Lakes and Wetlands Database (GLWD) y Global River Classification (GloRiC) in ArcGIS API For Python y Google Earth Engine.</h5>

 <h5 align="justify">
  Agrometeorology:
  
- Forecasting and evaluation of agrometeorological variables (precipitation, temperature, soil moisture) applying the models (AgrometShell, APSIM and DSSAT). </h5>

<h5 align="justify">
 GIS and cartography:
 
- Development of basic and thematic cartography, web maps and Apps in ArcGIS online using ESRI tools. </h5>


<h5 align="justify"> In my professional career, I have a solid experience in the acquisition and geoprocessing of geospatial data obtained through satellite imagery, aerial photography, drone, radar, etc., which allows me to offer a wide portfolio of useful solutions for spatial and temporal analysis, data management and decision making, using Python | ArcGIS API for Python | Google Earth Engine (GEE) | Javascript | ArcGIS Maps SDK for JavaScript |R - Rstudio | HTML and C++.
 </h5>

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 20 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Carlos Mendez"
  avatar : "assets/images/profile-modified.png"
  bio    : "Cadastral and Geodesic Engineer, MSc in Geosciences and Environment"
  links:
    - label: "E-mail"
      icon: "fa-solid fa-envelope"
      url: "carlos.mendez@unesp.br"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/carlos-andres-mendez-vallejo-oficialpage/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CarlosMendez1997Col"
    - label: "Youtube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@AndresMendez-ej3vv"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


algolia:
  # Exclude more files from indexing
  files_to_exclude:
    - index.html
    - index.md
    - excluded-file.html
    - _posts/2017-11-28-post-exclude-search.md
    - subdirectory/*.html
  
