title: Professional Portfolio 
email: carlos.mendez@unesp.br
description: Geosciences| Hydro energy | Hidrometeorology | Agrometeorology | Geotechnologies - GIS | GeoAI-ML-DL
twitter_username: username
github_username: CarlosMendez1997Col
minimal_mistakes_skin: neon
search: true

author:
  name   : "Carlos Mendez"
  avatar : "assets/images/profile-modified.png"
  bio    : "Cadastral and Geodesic Engineer, MSc in Geosciences and Environment"
  links:
    - label: "E-mail"
      icon: "fa-solid fa-envelope"
      url: "carlos.mendez@unesp.br"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/carlos-andres-mendez-vallejo-oficialpage/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CarlosMendez1997Col"
    - label: "Youtube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@AndresMendez-ej3vv"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

include:
  - _pages
  - .htaccess

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes



# Outputting
permalink: /:categories/:title/
paginate: 20 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true



  
