title: Professional Portfolio 
email: carlos.mendez@unesp.br
description: Geosciences| Hydro energy | Hidrometeorology | Agrometeorology | Geotechnologies - GIS | GeoAI-ML-DL
github_username: CarlosMendez1997Col
minimal_mistakes_skin: neon
search: true

author:
  name   : "Carlos Mendez"
  avatar : "assets/images/profile-modified.png"
  bio    : "Cadastral and Geodesic Engineer, MSc in Geosciences and Environment"
  links:
    - label: "ResearchGate"
      icon: "fa-brands fa-researchgate"
      url: "https://www.researchgate.net/profile/Carlos-Mendez-Vallejo"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://co.linkedin.com/in/carlos-mendez-oficialpage/es"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CarlosMendez1997Col"
    - label: "Youtube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@AndresMendez-ej3vv"

footer:
  links:
    - label: "ResearchGate"
      icon: "fa-brands fa-researchgate"
      url: "https://www.researchgate.net/profile/Carlos-Mendez-Vallejo"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://co.linkedin.com/in/carlos-mendez-oficialpage/es"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CarlosMendez1997Col"
    - label: "Youtube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@AndresMendez-ej3vv"

include:
  - _pages


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 20 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#pagination:
# Set enabled to true to use paginate v2
# enabled: true
#  debug: false
#  collection: 'posts'
#  per_page: 10
#  permalink: '/page/:num/'
#  title: ':title - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
#  category: 'posts'
#  tag: ''
#  locale: ''
#  trail:
# before: 2
# after: 2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


  
